-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.util.** { *; }
-keep class io.flutter.** { *; }
-keep class io.flutter.plugins.** { *; }
-keep class org.webrtc.** { *; }
-keep class net.sqlcipher.** { *; }
-dontwarn net.sqlcipher.**
